spring.application.name=careme

# CONEXIÓN DINÁMICA (Local y AWS)
spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT:localhost}:5432/${DB_NAME:careme_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' para desarrollo local/AWS Academy. 'validate' para producción real.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Obliga a Spring a esperar que las tablas existan antes de insertar los datos
spring.jpa.defer-datasource-initialization=true

# SWAGGER / OPENAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html